parameters:
- name: username
  type: string
- name: password
  type: string
- name: environment
  type: string
- name: workingDir
  type: string

stages:
  - stage: buildExpo
    displayName: 'Build Expo Project'
    jobs:
      - job:
        displayName: 'Build Expo'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '14.x'  

          - task: replacetokens@3
            displayName: 'Configure'
            inputs:
              targetFiles: |
                **/*.json
                **/*.config.js
                **/*env*'
              encoding: 'auto'
              writeBOM: true
              verbosity: 'detailed'
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTelemetry: true

          - task: Npm@1
            displayName: 'Restore NPM Packages'
            inputs:
              command: 'install'
              workingDir: ${{ parameters.workingDir }}

          - script: npx expo login -u ${{ parameters.username }} -p ${{ parameters.password }}
            displayName: 'Expo Login'

          - task: Npm@1
            displayName: 'Build Android'
            inputs:
              command: 'custom'
              workingDir: ${{ parameters.workingDir }}
              customCommand: 'run build:android'

          - task: Npm@1
            displayName: 'Build iOS'
            inputs:
              command: 'custom'
              workingDir: ${{ parameters.workingDir }}
              customCommand: 'run build:ios'

           - task: Npm@1
              displayName: 'Deploy to Google Play'
              inputs:
                command: 'custom'
                workingDir: ${{ parameters.workingDir }}
                customCommand: 'run deploy:android'               

            - task: Npm@1
                displayName: 'Deploy to Apple App Store'
                inputs:
                  command: 'custom'
                  workingDir: ${{ parameters.workingDir }}
                  customCommand: 'run deploy:ios'

                
          
  