parameters:
- name: stageId
  type: string
- name: displayName
  type: string
- name: project
  type: string

stages:
  - stage: ${{ parameters.stageId }}
    displayName: ${{ parameters.displayName }}
    jobs:
      - job:
        displayName: 'Execute'
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'env | sort'

          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '14.x'  

          - template: build-npm-project.yml@templates
            parameters: 
              appName: ${{ parameters.project }}
              workingDir: $(Pipeline.Workspace)\s