parameters:
- name: stageId
  type: string
- name: displayName
  type: string
- name: project
  type: string
- name: version
  type: string
  default: '14.x'


stages:
  - stage: ${{ parameters.stageId }}
    displayName: ${{ parameters.displayName }}
    jobs:
      - job:
        displayName: 'Execute'
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: ${{ parameters.version }}
          
          - template: publish-npm-project.yml@templates
            parameters:
              appName: ${{ parameters.project }}
              workingDir: $(Pipeline.Workspace)\s
              destination: 'dist'