parameters:
- name: jobId
  type: string
- name: buildId
  type: string
- name: displayName
  type: string
- name: project
  type: string
- name: server
  type: string
- name: database
  type: string
- name: username
  type: string
- name: password
  type: string
- name: backupPath
  type: string
- name: environment
  type: string

jobs:
- deployment: ${{ parameters.jobId }}
  displayName: ${{ parameters.displayName }}
  environment: 
    name: ${{ parameters.environment }}
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
          - template: ef-database-migration.yml@templates 
            parameters:
              buildId: ${{ parameters.buildId }}
              project: ${{ parameters.project }}
              server: ${{ parameters.server }}
              database: ${{ parameters.database }}
              username: ${{ parameters.username }}
              password: ${{ parameters.password }}
              backupPath: ${{ parameters.backupPath }}
    