parameters:
- name: jobId
  type: string
- name: displayName
  type: string
- name: appName
  type: string
- name: appPath
  type: string
- name: appEndpoint
  type: string
- name: environment
  type: string
- name: certificate
  type: string
- name: iisRoot
  type: string
- name: netFrameworkVersion
  type: string
- name: configuration
  type: string
- name: configPattern
  type: string

jobs:
- deployment: ${{ parameters.jobId }}
  displayName: ${{ parameters.displayName }}
  environment: 
    name: ${{ parameters.environment }}
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
          - template: pack-net-project.yml@templates
            parameters:
              project: ${{ parameters.appName }}
              netFrameworkVersion: ${{ parameters.netFrameworkVersion }}
              configuration: ${{ parameters.configuration }}
              configPattern: ${{ parameters.configPattern }}

          - template: iis-deployment.yml@templates
            parameters:
              iisAppName: ${{ parameters.appName }}
              iisAppPath: ${{ parameters.appPath }}
              iisRoot: ${{ parameters.iisRoot }}
              appEndpoint: ${{ parameters.appEndpoint }}
              environment: ${{ parameters.environment }}
              certificate: ${{ parameters.certificate }}
  